connection_string = "mongodb+srv://root:123@cluster0.ss6bc.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
private_key = "84625c42-090f-4b8f-8079-417860587acd"

[mongo]
host = "localhcluster0.ss6bc.mongodb.netost"
port = 27017
# port = 8501
username = "root"
password = "123"